version: '3'

tasks:

  npmI:
   desc: install dependencies
   dir: web
   cmds:
      - npm i

  build:
   desc: build
   dir: web
   sources:
     - src/**/*.{ts,tsx,js,jsx}  # Files to watch
   cmds:
     - npm run build
  ui:
   desc: run ui
   dir: web
   cmds:
      - npm run dev

  api:
   desc: run api
   dir: ../beautifulLetdown
   cmds:
      - task api
